export const API_ENDPOINTS = {
  posts: '/api/posts',
  agents: '/api/agents',
  user: '/api/users',
  reviews: '/api/reviews',
  blogs: '/api/blogs',
  accounts: '/api/media-accounts',
  members: '/api/members-details',
  FreqAskedQues: '/api/frequently-asked-question',
  aboutUsOverview: '/api/about-us-page',
  aboutUsSupport: '/api/about-us-support',
  veterence: '/api/support-veterence',
  impact: '/api/impact-page/stories',
  videoReview: '/api/video-review',
  ourStory: '/api/our-story',
  additionalSuccessStories: '/api/stories/additional-success-stories',
  howVeterencePCSServiceWorks: '/api/how-it-works/how-veterence-pcs-service-works',
  fetchActionItem: '/api/internship/fetch-action-item-list',
  fetchInternshipBenefits: '/api/internship/fetch-internship-benefits',
  fetchInternshipOffer: '/api/internship/fetch-internship-offer'
} as const