export const SALESFORCE_BASE_URL = process.env.VPCS_SALESFORCE_BASE_URL;
export const SALESFORCE_API_VERSION = process.env.SALESFORCE_API_VERSION;
export const SALESFORCE_LOGIN_BASE_URL = process.env.SALESFORCE_LOGIN_BASE_URL;
export const BASE_API_URL = process.env.NEXT_PUBLIC_API_BASE_URL;