"use client";
import { useEffect, useRef, useState, type FormEvent } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import LeadCaptureDialog from '@/components/redesign/LeadCaptureDialog';
import { calculateMovingBonus } from '@/lib/bonus/calculate';
import { captureAnalyticsEvent } from '@/lib/analytics/client';
import { RESOURCE_CATEGORIES, RESOURCE_TOOLS, RESOURCE_DOWNLOADS, CHECKLIST_SLUG, INSTALLATION_GUIDES, categoryCounts, normalizeResourceQuery, searchResources, type Resource } from '@/lib/resources/catalogue';
import ResourceIcon from './ResourceIcon';
import styles from './StephResources.module.css';
type Partner={id:string;name:string;url?:string;image:string;alt?:string};
const currency=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
function ResourceCard({resource}:{resource:Resource}) {
 return <article className={styles.resourceCard}>{resource.image && <Image src={resource.image} alt={resource.imageAlt || ''} width={420} height={240} className={styles.resourceImage}/>}<div className={styles.resourceContent}><span className={styles.badge}>{resource.kind==='article' ? resource.id===CHECKLIST_SLUG ? 'CHECKLIST' : 'GUIDE' : resource.kind==='download' ? 'FREE GUIDE' : 'TOOL'}</span><h3>{resource.title}</h3><p>{resource.description}</p>{resource.download ? <LeadCaptureDialog kind={resource.download} triggerLabel="Download Guide"/> : <Link className={styles.textLink} href={resource.href}>View {resource.id===CHECKLIST_SLUG ? 'Checklist' : resource.kind==='tool' ? 'Tool' : 'Guide'} <span aria-hidden="true">→</span></Link>}</div></article>;
}
export default function StephResources({articles,partners}:{articles:Resource[];partners:Partner[]}) {
 const router=useRouter(), params=useSearchParams(), searchRef=useRef<HTMLInputElement>(null);
 const q=normalizeResourceQuery(params.get('q') || ''), rawCategory=params.get('category') || '';
 const category=RESOURCE_CATEGORIES.some(item=>item.id===rawCategory)?rawCategory:'';
 const [draft,setDraft]=useState(q),[limit,setLimit]=useState(12),[bonusOpen,setBonusOpen]=useState(false),[homePrice,setHomePrice]=useState('300000'),[allPartners,setAllPartners]=useState(false);
 const browsing=Boolean(q || category || params.get('view')==='all');
 const catalogue=[...RESOURCE_TOOLS,...RESOURCE_DOWNLOADS,...articles];
 const results=searchResources(catalogue,q,category),counts=categoryCounts(articles);
 useEffect(()=>{setDraft(q);setLimit(12);},[q,category]);
 useEffect(()=>{const reveal=()=>{if(window.location.hash==='#move-in-bonus')setBonusOpen(true);};reveal();window.addEventListener('hashchange',reveal);return()=>window.removeEventListener('hashchange',reveal);},[]);
 function search(event:FormEvent){event.preventDefault();const query=normalizeResourceQuery(draft);const next=new URLSearchParams();if(query)next.set('q',query);else next.set('view','all');router.push(`/pcs-resources?${next}#resource-library`,{scroll:true});captureAnalyticsEvent('cta_clicked',{cta_id:'pcs_resources_search',cta_label:'Search resources',has_query:Boolean(query),page_type:'pcs_resources'});}
 function reset(){setDraft('');router.push('/pcs-resources#resource-library',{scroll:false});searchRef.current?.focus();}
 function openBonus(){setBonusOpen(true);router.push('/pcs-resources#move-in-bonus');}
 const checklist=articles.find(item=>item.id===CHECKLIST_SLUG);
 const tools=[...RESOURCE_TOOLS,checklist?{...checklist,title:'PCS Checklist',description:'The ultimate PCS checklist to keep your move organized and stress-free.'}:null].filter((item):item is Resource=>Boolean(item));
 const featuredSlugs=[CHECKLIST_SLUG,'2026-bah-rates-what-changed-and-how-to-check-yours','pcs-to-your-first-duty-station-guide'];
 const featuredCopy=[['Ultimate PCS Checklist','Everything you need to know before, during, and after your PCS.'],['2026 BAH Rates Guide','What changed in 2026 and how to confirm your BAH by rank and location.'],['First Duty Station Guide','Tips for planning a smooth move to your first duty station.']];
 const featuredPhotos=[['packing','Preparing boxes for a military move'],['house','Home exterior'],['duty-station','Service member with child']];
 const featured=[...featuredSlugs.flatMap((slug,index)=>{const article=articles.find(item=>item.id===slug);return article?[{...article,title:featuredCopy[index]![0]!,description:featuredCopy[index]![1]!,image:`/images/redesign/resources-featured-${featuredPhotos[index]![0]}.png`,imageAlt:featuredPhotos[index]![1]!}]:[];}),{...RESOURCE_DOWNLOADS[0]!,image:'/images/redesign/resources-featured-signing.png',imageAlt:'Completing home purchase paperwork'}];
 const price=Number(homePrice),hasPrice=homePrice!=='' && Number.isFinite(price) && price>0,bonus=hasPrice?calculateMovingBonus(price):null;
 return <main className={`steph-design ${styles.page}`}>
  <section className={styles.hero} aria-labelledby="resources-title"><div className={styles.container}><p className={styles.eyebrow}>RESOURCES & TOOLS</p><h1 id="resources-title">Military Moving<br/>Toolkit</h1><p className={styles.heroCopy}>Everything you need before, during, and after<br className={styles.desktopBreak}/> your PCS — all in one place.</p><form onSubmit={search} role="search" className={styles.search}><label className={styles.srOnly} htmlFor="resource-search">Search resources, guides, and tools</label><input ref={searchRef} id="resource-search" type="search" value={draft} onChange={event=>setDraft(event.target.value)} placeholder="Search resources, guides, tools…" maxLength={160}/><button type="submit" aria-label="Search resources"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></svg></button></form></div></section>
  <div className={styles.container}>
   <nav className={styles.selector} aria-label="What do you need today?"><h2>WHAT DO YOU NEED TODAY?</h2><div className={styles.selectorGrid}>{[RESOURCE_CATEGORIES[0],RESOURCE_CATEGORIES[3],RESOURCE_CATEGORIES[1],RESOURCE_CATEGORIES[4]].map(item=><Link key={item.id} href={`/pcs-resources?category=${item.id}#resource-library`} className={category===item.id?styles.selected:''} aria-current={category===item.id?'page':undefined}><ResourceIcon name={item.icon}/><span>{item.label}</span></Link>)}<Link href="/bah-calculator"><ResourceIcon name="calculator"/><span>BAH Calculator</span></Link><a href="#partners"><ResourceIcon name="tag"/><span>Veteran Resources</span></a></div></nav>
   <section className={styles.section} aria-labelledby="tools-title"><header className={styles.heading}><h2 id="tools-title">FEATURED MILITARY TOOLS</h2><p>Powerful tools and calculators to help you plan your move with confidence.</p></header><div className={styles.toolsGrid}>{tools.map((tool,index)=><article className={styles.toolCard} key={tool.id} id={tool.id==='bah'?'bah-calculator':undefined}><span className={styles.iconCircle}><ResourceIcon name={['home','shield','gift','checklist'][index] || 'home'}/></span><h3>{tool.title}</h3><p>{tool.description}</p>{tool.id==='bonus'?<button className="steph-button" type="button" onClick={openBonus}>See My Bonus</button>:<Link className="steph-button" href={tool.href}>{tool.id==='bah'?'Calculate BAH':tool.id==='va-calculator'?'Calculate Now':'View Checklist'}</Link>}</article>)}</div>
    <div id="move-in-bonus" className={styles.bonus}><button className={styles.bonusToggle} type="button" aria-expanded={bonusOpen} aria-controls="resource-bonus-panel" onClick={()=>{setBonusOpen(value=>!value);if(!bonusOpen)router.replace('/pcs-resources#move-in-bonus',{scroll:false});}}>Estimated VeteranPCS Move-In Bonus <span aria-hidden="true">{bonusOpen?'−':'+'}</span></button>{bonusOpen && <div id="resource-bonus-panel" className={styles.bonusPanel}><div><label htmlFor="resource-home-price">Planned home price</label><input id="resource-home-price" type="text" inputMode="numeric" value={homePrice} onChange={event=>setHomePrice(event.target.value.replace(/[^0-9]/g,'').slice(0,8))}/><label className={styles.srOnly} htmlFor="resource-home-slider">Adjust planned home price</label><input id="resource-home-slider" type="range" min={50000} max={1000000} step={1000} value={Math.min(1000000,Math.max(50000,price))} onChange={event=>setHomePrice(event.target.value)}/></div><div><p>Your estimated bonus</p><output aria-live="polite">{bonus===null?'—':currency(bonus)}</output>{!hasPrice && <p>Enter a home price greater than $0.</p>}</div><Link className="steph-button" href="/contact-agent">Find an Agent</Link><p className={styles.bonusNote}>Bonus amounts are estimates and may vary based on final purchase price and actual commission rates.</p></div>}</div>
   </section>
   <section className={styles.section} aria-labelledby="category-title"><header className={styles.heading}><h2 id="category-title">BROWSE RESOURCES BY CATEGORY</h2><p>Find guides, tips, and tools for every step of your military move.</p></header><div className={styles.categoriesGrid}>{RESOURCE_CATEGORIES.map(item=><Link key={item.id} className={styles.categoryCard} href={`/pcs-resources?category=${item.id}#resource-library`}><ResourceIcon name={item.icon}/><h3>{item.label}</h3><span>{counts[item.id]} Guides <span aria-hidden="true">›</span></span></Link>)}</div></section>
   <section id="resource-library" className={styles.section} aria-labelledby="library-title"><header className={styles.heading}><h2 id="library-title">{browsing?q?'SEARCH RESULTS':category?RESOURCE_CATEGORIES.find(item=>item.id===category)?.label.toUpperCase():'ALL RESOURCES':'FEATURED RESOURCES'}</h2><p>{browsing?`${results.length} ${results.length===1?'resource':'resources'}${q?` for “${q}”`:''}`:'Helpful guides for military families.'}</p></header>{browsing && <button className={styles.reset} type="button" onClick={reset}>Reset search and filters</button>}{browsing && !results.length?<div className={styles.empty} role="status"><h3>No resources found</h3><p>Try a different search, such as “PCS checklist” or “VA loan”.</p></div>:<div className={styles.resourcesGrid}>{(browsing?results.slice(0,limit):featured).map(resource=><ResourceCard key={resource.id} resource={resource}/>)}</div>}<div className={styles.center}>{browsing?limit<results.length && <button className="steph-button steph-button-outline" type="button" onClick={()=>setLimit(value=>value+12)}>Show More Resources</button>:<Link className="steph-button steph-button-outline" href="/pcs-resources?view=all#resource-library">View All Resources</Link>}</div></section>
   <section className={styles.downloads} aria-label="Free downloadable guides"><Image src="/images/redesign/guide-covers.webp" alt="VeteranPCS free homebuyer and VA loan guides" width={210} height={145}/><div><h2>FREE GUIDES FOR YOUR NEXT HOME</h2><p>Start with our First-Time Homebuyer Guide or VA Loan Guide.</p></div><LeadCaptureDialog kind="homebuyer-guide" triggerLabel="Get Homebuyer Guide"/><LeadCaptureDialog kind="va-guide" triggerLabel="Get VA Loan Guide"/></section>
   <section className={styles.journey} aria-labelledby="journey-title"><div><p className={styles.eyebrow}>YOUR PCS JOURNEY</p><h2 id="journey-title">We’re Here for Every Step</h2><p>Use our tools and resources to plan with confidence and connect with a local expert when you’re ready.</p></div><ol>{[{title:'Plan Your Budget',copy:'Use our calculators to plan your move.',icon:'dollar',href:'/va-loan-calculator'},{title:'Get Prepared',copy:'Checklists and guides keep you on track.',icon:'checklist',href:`/blog/${CHECKLIST_SLUG}`},{title:'Find Your Home',copy:'Explore areas and homes near your base.',icon:'home',href:'/pcs-resources?category=duty-stations#resource-library'},{title:'Work With an Expert',copy:'Get matched with a trusted veteran agent.',icon:'users',href:'/contact-agent'}].map((step,index)=><li key={step.title}><span className={styles.stepNumber}>{index+1}</span><ResourceIcon name={step.icon}/><Link href={step.href}>{step.title}</Link><p>{step.copy}</p></li>)}</ol></section>
   <section className={styles.section} aria-labelledby="installations-title"><header className={styles.heading}><h2 id="installations-title">EXPLORE BY DUTY STATION</h2><p>Find base guides, housing info, and resources for your location.</p></header><div className={styles.installationsGrid}>{INSTALLATION_GUIDES.map(([title,slug])=>{const article=articles.find(item=>item.id===slug);return article?<Link key={slug} href={article.href} className={styles.installation}>{article.image && <Image src={article.image} alt="" fill sizes="(max-width:767px) 45vw, 170px"/>}<span>{title}</span></Link>:null;})}<Link className={styles.moreTile} href="/blog/category/us-military-bases">View All<br/>Base Guides <span aria-hidden="true">›</span></Link></div></section>
   <section id="partners" className={styles.section} aria-labelledby="partners-title"><header className={styles.heading}><h2 id="partners-title">TRUSTED MILITARY RESOURCES</h2><p>Explore organizations and businesses that support military families.</p></header><div className={styles.partnersGrid}>{(allPartners?partners:partners.slice(0,6)).map(partner=><div className={styles.partner} key={partner.id}>{partner.url?<a href={partner.url} target="_blank" rel="noopener noreferrer"><Image src={partner.image} alt={partner.alt || partner.name} width={190} height={76}/><span>{partner.name}</span></a>:<><Image src={partner.image} alt={partner.alt || partner.name} width={190} height={76}/><span>{partner.name}</span></>}</div>)}{!allPartners && <button className={styles.moreTile} type="button" onClick={()=>setAllPartners(true)}>View All<br/>Resources <span aria-hidden="true">›</span></button>}</div><div className={styles.partnerLinks}><a href="https://www.hiringourheroes.org/">Hiring Our Heroes</a><a href="https://www.hireheroesusa.org/">Hire Heroes USA</a><Link href="/military-spouse">Military Spouse Resources</Link><a href="https://installations.militaryonesource.mil/search?program-service=26/view-by=ALL">Military OneSource Sponsorship</a></div></section>
   <section className={styles.finalCta}><div><h2>Still have questions?</h2><p>Our team of Veteran and Military Spouse agents<br className={styles.desktopBreak}/> is here to help you every step of the way.</p></div><div><Link className="steph-button" href="/contact-agent">Match With an Agent</Link><p>Our service is 100% FREE for military families.</p></div></section>
  </div>
 </main>;
}
