import Image from 'next/image';
import Link from 'next/link';
import { MDXRemote } from 'next-mdx-remote/rsc';
import { createBlogMdxComponents } from '@/mdx-components';
import { mdxOptions } from '@/lib/blog/mdx-options';
import { extractTocHeadings, readingTimeMinutes } from '@/lib/blog/mdx';
import { splitMdxAtMidpoint } from '@/lib/blog/splitMdxAtMidpoint';
import { buildContactCtaHref } from '@/lib/contactAgentUrl';
import type { BlogPost, ResolvedAuthor } from '@/lib/blog/types';
import { formatDate } from '@/utils/helper';
import { SITE_URL } from '@/lib/siteUrl';
import accounts from '@/content/_data/site/media_account.json';
import reviews from '@/public/json/reviews.json';
import ArticleLink, { type ArticleContext } from './ArticleLink';
import { ArticleCapture, ArticleShare, ArticleTestimonial, ArticleToc } from './ArticleActions';
import styles from './StephArticle.module.css';
const resources=[
  {title:'PCS Checklist',description:'Step-by-step checklist to keep your move stress-free.',href:'/blog/the-ultimate-pcs-checklist-and-timeline-for-active-duty-military-personnel',label:'Get the checklist',icon:'checklist'},
  {title:'BAH Calculator',description:'See your basic allowance for housing by location.',href:'/bah-calculator',label:'Calculate now',icon:'calculator'},
  {title:'Military Base Guides',description:'Find housing information and resources near your base.',href:'/blog/category/us-military-bases',label:'Explore bases',icon:'check'},
  {title:'VA Loan Guides',description:'Learn more about making the most of your VA loan.',href:'/va-loan-help',label:'VA Loan',icon:'loan'},
];
function Icon({ kind }: { kind:string }) {
  return <svg aria-hidden="true" viewBox="0 0 32 32" className={styles.icon} fill="none" stroke="currentColor" strokeWidth="2"><path d={kind==='home'?'m3 15 13-11 13 11M7 13v15h7v-9h4v9h7V13':kind==='checklist'?'M10 5H5v24h22V5h-5M10 3h12v6H10ZM10 14h12M10 19h12M10 24h12':kind==='calculator'?'M6 3h20v26H6ZM10 7h12v5H10ZM10 17h2m6 0h2m-10 6h2m6 0h2':kind==='loan'?'M16 4v24M23 9c-5-7-15-3-13 3 1 3 11 2 12 6 3 7-9 10-14 4':kind==='people'?'M3 28c0-11 26-11 26 0M11 11a5 5 0 1 0 10 0 5 5 0 1 0-10 0':kind==='follow'?'M12 28H5V14h7ZM12 14l6-11c4 0 2 8 2 10h8l-3 15H12Z':'m7 16 6 6 12-14'}/></svg>;
}
function Socials() {return <div className={styles.socials}>{accounts.map(account=><a href={account.link} key={account._id} aria-label={`VeteranPCS on ${account.name}`} target="_blank" rel="noopener noreferrer"><Image src={`/icon/${account.icon}`} alt="" width={30} height={30}/></a>)}</div>;}
function HelpfulResources({ context, sidebar=false }: { context:ArticleContext; sidebar?:boolean }) {
  return <section className={sidebar ? styles.sidebarResources : styles.resources} aria-label={sidebar?'More helpful resources':'Helpful PCS Resources'}><h2>{sidebar?'Helpful Resources':'Helpful PCS Resources'}</h2><div>{resources.map(item=><ArticleLink key={item.title} href={item.href} id={`blog_resource_${item.icon}_${sidebar?'sidebar':'top'}`} context={context}><Icon kind={item.icon}/><span><strong>{item.title}</strong>{!sidebar&&<><p>{item.description}</p><small>{item.label} →</small></>}</span></ArticleLink>)}</div>{sidebar&&<ArticleLink href="/pcs-resources" id="blog_sidebar_all_resources" context={context}>View all resources →</ArticleLink>}</section>;
}
function ContextCta({ context, label, href }: { context:ArticleContext; label:string; href:string }) {
  return <section className={styles.contextCta} aria-label="Plan your next move"><Icon kind="home"/><div><h2>Planning Your Next Move?</h2><p>Connect with Veteran &amp; Military Spouse Real Estate Agents and VA Loan Experts You Can Trust.</p></div><div><ArticleLink href={href} context={context} id={context.partnerType==='agent'?'blog_details_find_agent':'blog_details_find_lender'} intent={`contact_${context.partnerType}`} className={styles.button}>{label}</ArticleLink><small>Totally FREE to use!</small></div></section>;
}
function GuidePromo() {return <section className={styles.guide} aria-label="Free homebuyer guide"><Image src="/images/redesign/guide-covers.webp" width={200} height={160} alt="First-Time Homebuyer and VA Loan guide covers"/><div><h2>Free First-Time Homebuyer Guide</h2><p>Make your move less stressful with our step-by-step first-time homebuyer guide.</p><ArticleCapture kind="homebuyer-guide" button="Get My Free Guide"/><small>We respect your privacy. Unsubscribe anytime.</small></div></section>;}
function Bonus({ context }: { context:ArticleContext }) {return <section className={styles.bonus}><h2>VeteranPCS<br/>Bonus</h2><p>Receive up to<br/><strong>$4,000 BACK</strong></p><p>When you buy or sell<br/>with VeteranPCS</p><ArticleLink href="/pcs-resources#move-in-bonus" id="blog_sidebar_bonus" context={context} className={styles.button}>Learn More</ArticleLink><Image src="/images/redesign/blog-bonus-family.webp" alt="VeteranPCS family receiving a move-in bonus check" width={460} height={430}/></section>;}
export default function StephArticle({ blog, resolvedAuthor, stateSlug, intent, category, related }: { blog:BlogPost; resolvedAuthor:ResolvedAuthor; stateSlug:string|null; intent:'agent'|'lender'; category:{label:string;slug:string}|null; related:BlogPost[] }) {
  const context:ArticleContext={contentSlug:blog.slug,stateSlug,partnerType:intent};
  const href=buildContactCtaHref({stateSlug,form:intent});
  const stateName=stateSlug ? stateSlug.split('-').map(word=>word.charAt(0).toUpperCase()+word.slice(1)).join(' ') : null;
  const label=`Find ${intent==='agent'?'an agent':'a lender'}${stateName?` in ${stateName}`:''}`;
  const firstSplit=splitMdxAtMidpoint(blog.content), secondSplit=splitMdxAtMidpoint(firstSplit.second);
  const parts=[firstSplit.first,secondSplit.first,secondSplit.second];
  const headings=extractTocHeadings(blog.content);let headingOffset=0;
  const bodies=parts.map((part,index)=>{const count=extractTocHeadings(part).length;const ids=headings.slice(headingOffset,headingOffset+count);headingOffset+=count;return part?<div key={index} data-article-body={index}><MDXRemote source={part} components={createBlogMdxComponents({resolvedAuthor,headingIds:ids,contentSlug:blog.slug})} options={mdxOptions}/></div>:null;});
  const quotes=reviews.reviews.filter(review=>['Breanna Walker','Hailey Jensen'].includes(review.reviewer.displayName)&&review.comment).map(review=>({name:review.reviewer.displayName,text:review.comment??''}));
  return <main className={styles.page} data-steph-article>
    <div className={styles.grid}><div className={styles.mainColumn}>
      <header className={styles.articleHeader}><div><nav aria-label="Breadcrumb" className={styles.breadcrumb}><Link href="/">Home</Link><span>/</span><Link href="/blog">Blog</Link>{category&&<><span>/</span><ArticleLink href={`/blog/category/${category.slug}`} context={context} id="blog_breadcrumb_category">{category.label}</ArticleLink></>}</nav><span className={styles.category}>{category?.label??'PCS Tips'}</span><h1>{blog.title}</h1><div className={styles.byline}>{resolvedAuthor.kind==='salesforce'?<ArticleLink href={resolvedAuthor.contactHref} context={{...context,stateSlug:resolvedAuthor.stateSlug,partnerType:resolvedAuthor.role}} id="blog_author_contact" intent={`contact_${resolvedAuthor.role}`} partnerSalesforceId={resolvedAuthor.salesforceId}>By {resolvedAuthor.name}</ArticleLink>:<span>By VeteranPCS</span>}<span>•</span><time dateTime={blog.publishedAt}>{formatDate(blog.publishedAt)}</time><span>•</span><span>{readingTimeMinutes(blog.content)} min read</span></div><p className={styles.summary}>{blog.description??blog.metaDescription}</p><ArticleShare title={blog.title} url={`${SITE_URL}/blog/${blog.slug}`} image={`${SITE_URL}${blog.mainImage?.src??'/assets/BlogpostImage.png'}`}/></div><Image src={blog.mainImage?.src??'/assets/BlogpostImage.png'} alt={blog.mainImage?.alt??blog.title} width={620} height={600} priority className={styles.heroImage}/></header>
      <HelpfulResources context={context}/><ArticleToc headings={headings} mobile/>
      <article className={styles.body} aria-label="Article body">{bodies[0]}<ContextCta context={context} label={label} href={href}/>{bodies[1]}<GuidePromo/>{bodies[2]}</article>
      <ArticleTestimonial quotes={quotes}/>
      <section className={styles.conversions} aria-label="Your next steps"><div><Icon kind="home"/><h2>Ready to Move?</h2><p>Let us connect you with {intent==='agent'?'an agent':'a VA loan expert'} for your next duty station.</p><ArticleLink href={href} id="blog_conversion_contact" intent={`contact_${intent}`} context={context} className={styles.button}>{label}</ArticleLink><small>It’s free. No obligation.</small>{stateSlug&&intent==='agent'&&<ArticleLink href={`/${stateSlug}?source=blog&blog_slug=${encodeURIComponent(blog.slug)}`} id="blog_find_agent_in_state" intent="state_agent_search" context={context}>Browse {stateName} agents →</ArticleLink>}</div><div><Icon kind="checklist"/><h2>Not Moving Yet?</h2><p>Get PCS tips, VA loan advice, and duty station updates delivered to you.</p><ArticleCapture compact/><small>Unsubscribe anytime.</small></div><div><Icon kind="follow"/><h2>Follow VeteranPCS</h2><p>Daily tips, videos, and resources made for military families.</p><Socials/><ArticleLink href="#article-social-platforms" id="blog_social_all" context={context}>See all platforms →</ArticleLink></div><div><Icon kind="loan"/><h2>VeteranPCS Bonus</h2><p>Receive up to $4,000 back when you buy or sell with us!</p><ArticleLink href="/pcs-resources#move-in-bonus" id="blog_conversion_bonus" context={context} className={styles.button}>Learn More</ArticleLink></div></section>
      <section className={styles.related} aria-label="Related articles"><h2>Other Articles You May Also Like</h2><div>{related.slice(0,4).map(post=><ArticleLink href={`/blog/${post.slug}`} id="blog_related_card" context={{...context,contentSlug:post.slug}} key={post.slug}><Image src={post.mainImage?.src??'/assets/BlogpostImage.png'} alt={post.mainImage?.alt??post.title} width={320} height={220}/><h3>{post.shortTitle??post.title}</h3><p>{readingTimeMinutes(post.content)} min read</p></ArticleLink>)}</div></section>
      <section className={styles.finalCta}><h2>We’re Here for Your Next Move</h2><p>Connect with a trusted Veteran or Military Spouse {intent==='agent'?'agent':'VA loan expert'} today!</p><ArticleLink href={href} id="blog_final_contact" intent={`contact_${intent}`} context={context} className={styles.button}>{label}</ArticleLink><div><span>Veteran &amp; Military Spouse Agents</span><span>No Cost to You</span><span>VeteranPCS Bonus</span><span>Give Back to Military Families</span></div></section>
    </div><aside className={styles.sidebar} aria-label="Article resources"><ArticleToc headings={headings}/><section className={styles.newsletter}><span aria-hidden="true">✉</span><h2>Get VeteranPCS Updates<br/>Delivered to You</h2><p>Tips, checklists, and resources for military families</p><ArticleCapture/><small>Unsubscribe anytime</small></section><section id="article-social-platforms" className={styles.follow}><h2>Follow VeteranPCS</h2><p>Daily tips, videos &amp; updates made for military families.</p><Socials/></section><HelpfulResources context={context} sidebar/><Bonus context={context}/></aside></div>
    <div className={styles.sticky} data-cta-id={`blog_mobile_sticky_${intent}`}><ArticleLink href={href} id={`blog_mobile_sticky_${intent}`} intent={`contact_${intent}`} context={context} className={styles.button}>{label}</ArticleLink></div>
  </main>;
}
