import {describe,it,expect} from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import matter from 'gray-matter';
import type {BlogPost} from '@/lib/blog/types';
import {buildResourceCatalogue,categoryCounts,searchResources,normalizeResourceQuery,RESOURCE_CATEGORIES,RESOURCE_TOOLS,RESOURCE_DOWNLOADS,INSTALLATION_GUIDES,CHECKLIST_SLUG} from '../catalogue';
const post=(changes:Partial<BlogPost>={}):BlogPost=>({title:'PCS checklist for a VA home',slug:'pcs-checklist',metaTitle:'PCS',metaDescription:'Plan your move',publishedAt:'2026-01-01',component:'PCS Help',categories:['PCS Help','Real Estate Insights'],mainImage:{src:'/images/checklist.webp',alt:'Moving boxes'},author:{},content:'',filepath:'',...changes});
describe('resources catalogue',()=>{
 it('maps primary and secondary taxonomy to the same category counts and filters',()=>{const resources=buildResourceCatalogue([post(),post({slug:'mortgage',component:'VA Loan Help',categories:['VA Loan Help']})]);expect(categoryCounts(resources)).toEqual({'buying-home':1,'pcs-planning':1,'military-finance':0,'va-loan-help':1,'duty-stations':0});expect(searchResources(resources,'','buying-home').map(item=>item.id)).toEqual(['pcs-checklist']);});
 it('counts an article only once when component and secondary category match',()=>expect(categoryCounts(buildResourceCatalogue([post()]))['pcs-planning']).toBe(1));
 it('does not count tools or downloads as guides',()=>expect(categoryCounts([...RESOURCE_TOOLS,...RESOURCE_DOWNLOADS])['va-loan-help']).toBe(0));
 it('searches all query terms across title and description without case sensitivity',()=>{const resources=buildResourceCatalogue([post(),post({slug:'bah',title:'Basic allowance',metaDescription:'PCS pay grade'})]);expect(searchResources(resources,'  pCs   CHECKLIST ').map(item=>item.id)).toEqual(['pcs-checklist']);expect(searchResources(resources,'PCS unicorn')).toEqual([]);});
 it('ranks title matches ahead of description matches while retaining stable ties',()=>{const resources=buildResourceCatalogue([post({slug:'description',title:'Plan your move',metaDescription:'Checklist'}),post({slug:'title',title:'Checklist',metaDescription:'Move'})]);expect(searchResources(resources,'checklist')[0]?.id).toBe('title');});
 it('combines query and category filters',()=>{const resources=buildResourceCatalogue([post()]);expect(searchResources(resources,'checklist','va-loan-help')).toEqual([]);expect(searchResources(resources,'checklist','pcs-planning')).toHaveLength(1);});
 it('normalizes empty query, whitespace and maximum query length',()=>{expect(normalizeResourceQuery('  VA   loan ')).toBe('VA loan');expect(normalizeResourceQuery('  ')).toBe('');expect(normalizeResourceQuery('x'.repeat(200))).toHaveLength(160);});
 it('projects cards without body content and uses description rather than inventing ratings',()=>{const resource=buildResourceCatalogue([post({description:'Verified description',shortTitle:'Short checklist',content:'PRIVATE BODY'})])[0];expect(resource?.title).toBe('Short checklist');expect(resource?.description).toBe('Verified description');expect(resource).not.toHaveProperty('content');expect(resource).not.toHaveProperty('rating');});
 it('uses existing installation, checklist, featured articles and guide downloads',()=>{for(const slug of [...INSTALLATION_GUIDES.map(item=>item[1]),CHECKLIST_SLUG,'2026-bah-rates-what-changed-and-how-to-check-yours','pcs-to-your-first-duty-station-guide']){const file=path.join(process.cwd(),'content/blog',`${slug}.mdx`);expect(fs.existsSync(file),slug).toBe(true);expect(matter(fs.readFileSync(file,'utf8')).data.slug).toBe(slug);}for(const file of ['VA-Loan-Guide.pdf','first-time-home-buyer-guide.pdf'])expect(fs.existsSync(path.join(process.cwd(),'public/downloads',file))).toBe(true);expect(RESOURCE_CATEGORIES).toHaveLength(5);});
});
